### ISSUE TITLE
Using for background audio?

### ISSUE THREAD

**Issue by jasongrishkoff** [vikeri/react-native-background-job#1]
> On the native side it uses JobScheduler which means that the jobs can't be scheduled exactly and for Android 23+ they fire at most once per 15 minutes +-5 minutes. 

So is it safe to say that this wouldn't be a good tool to use for managing background audio? (eg, getting a playlist to switch to the next song while backgrounded).

**Comment by vikeri** [comment]
That is correct, this uses `JobScheduler` which schedules the job to run at specified intervals. You would need to trigger the HeadlessJS from Java yourself from the input event you need (eg. pressing a next button on your headset).

**Comment by vikeri** [comment]
This has now been enabled with an experimental `alwaysRunning` flag. Still very much alpha quality though. See: https://github.com/vikeri/react-native-background-job/releases/tag/v1.1.3-0

**Comment by vikeri** [comment]
This should be fixed by https://github.com/vikeri/react-native-background-job/pull/20
