### ISSUE TITLE
Compatibility with newer version of react-native?

### ISSUE THREAD

**Issue by jeromegrosse** [vikeri/react-native-background-job#10]
Is there any reason why this library require exclusively 0.36.0?

**Comment by vikeri** [comment]
No that is my bad, it works for newer versions of RN as well. There is a PR correcting this, haven't had the time to get to it yet though.

**Comment by vikeri** [comment]
Should be solved by https://github.com/vikeri/react-native-background-job/pull/15/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
