### ISSUE TITLE
is just work a min then it not working

### ISSUE THREAD

**Issue by tiyunchen** [vikeri/react-native-background-job#101]
i have a problem is  when my app run in background. The background-job just work only a min then it does't work . i don't know why ?
my device is google pixel-xl ,  the android version is 8.1 
here is my code 
`BackgroundJob.register({
      jobKey: 'mybjob',
      job: () => {this.backGroundAction()},
    });
    BackgroundJob.schedule({
      jobKey: 'mybjob',
      period: 5000,
      timeout:5000,
      exact: true,
      allowWhileIdle:true
    });`

**Comment by tiyunchen** [comment]
i tested in xiaomi 4  , it work perfect, xiaomi 4 android version is 6 ,may be it can't work on android N

**Comment by vikeri** [comment]
Closing since it's duplicate
