### ISSUE TITLE
Run Background Task Only When Internet Connection Is Available 

### ISSUE THREAD

**Issue by prasanthyejje** [vikeri/react-native-background-job#103]
My Background  job is calling irrespective of internet connection state.  I want to schedule the task when internet is available.
--> when device get back an internet connection, i have to do the scheduled task even when app is in foreground state.
--> i want to call this scheduled background job when device is connected to internet connection.

**Current Behaviour:**
 --> scheduled task is working when app is background state.( Even when internet is not-connected )

**Expected Bahaviour:** 
-->  Scheduled Task Should Execute When Device Connected To Internet Irrespective of App State( both Background And Foreground State).

**### I tried with this code :+1: ** 

    BackgroundJob.schedule({
                    jobKey: regularJobKey,
                    period: 10 * 1000,
                    networkType: NETWORK_TYPE_ANY
                });

---> But i Am getting An ERROR: **expected dynamic type `double', but had type `string' (constructing arguments for BackgroundJob.schedule at argument index 5)**

@vikeri @hkairi  guys could you help me, i've been searching for the solution since a week.

**### _Thanks In Advance._**

**### More Info About My Project Specification :+1: **

Dependency Version : "react-native-background-job": "^2.1.1",
version of RN is: 0.50.3
react-native-cli: 2.0.1
My Device : windows-7, 64-bit , 8GB RAM

**Comment by imran1992** [comment]
Try this way:
`networkType: BackgroundJob.NETWORK_TYPE_ANY`

Because React native don't know what is `NETWORK_TYPE_ANY`.
`NETWORK_TYPE_ANY` is a const given in this `react-native-background-job` package.

**Comment by prasanthyejje** [comment]
Tq @imran1992 . it's Working.

**Comment by vikeri** [comment]
Thanks @imran1992 for the help. Closing this.
