### ISSUE TITLE
Run Background Task when app is on closed and foreground state. 

### ISSUE THREAD

**Issue by prasanthyejje** [vikeri/react-native-background-job#105]
---> i want to run  react-native-background-job when application is on foreground as well as closed state.
---> this should happen when device is connected to internet.

**my code is** :     BackgroundJob.schedule({
                    jobKey: regularJobKey,
                    period: 5 * 1000,
                    networkType: BackgroundJob.NETWORK_TYPE_ANY,  
                    allowExecutionInForeground: true
                }); 

**Current Behaviour**: 
---> schedule Job is working when app is opened(foreground state). but not runing when app is closed.
---> In emulator  **Expected Bahaviour** is working fine, but not working in mobile device.

**Expected Bahaviour:** 
---> scheduled task should work when app is closed and app is open( in foreground state).

please help me  @imran1992   @vikeri @toteto @hkairi @Looveh @Looveh @toteto @MaximilianKindshofer @cristianocca @ivan-branets

### Thanks In Advance.

**### More Info About My Project Specification **

Dependency Version : "react-native-background-job": "^2.1.1",
version of RN is: 0.50.3
react-native-cli: 2.0.1
My Device : windows-7, 64-bit , 8GB RAM

**Comment by vikeri** [comment]
@prasanthyejje Could you create an example repo where this issue exists so that we can debug it?

**Comment by Daniyal-Tariq** [comment]
react-native-background-job is not working run in android API 28

**Comment by vikeri** [comment]
If this is related to #129 I'll close this issue and keep the other one open.

**Comment by Mangaleswarisakthi** [comment]
> react-native-background-job is not working run in android API 28

the same issue for me how to handle that

**Comment by tnshgarg** [comment]
Have you guys got anything on this ???
