### ISSUE TITLE
Is there a way to run a task right after device reboot?

### ISSUE THREAD

**Issue by natimenashe** [vikeri/react-native-background-job#116]
Great repo by the way.

**Comment by codemeall** [comment]
@natimenashe were you able to run the task after reboot?

**Comment by natimenashe** [comment]
No, i didn't find another react native repo that perform task on device boot.
Due to lack of time i have implemented a workaround instead of running task on device boot.

**Comment by rasheedk** [comment]
you should avoid 'exact' in parameters and  use 'persist' for enabling on reboot.

It's clearly mentioned in read me.

**Comment by kishansbs** [comment]
> you should avoid 'exact' in parameters and use 'persist' for enabling on reboot.
> 
> It's clearly mentioned in read me.

not working after reboot -- device redmi 7
