### ISSUE TITLE
current ios native module

### ISSUE THREAD

**Issue by rbembleton** [vikeri/react-native-background-job#13]
Hey,

I'm getting an error when I import the module on iOS. I'm aware that the functionality isn't there yet, but I'd rather not have to make two separate files to handle my main app logic. 

I was able to fix the problem if I did this:

```import { NativeModules, AppRegistry, Platform } from "react-native"; // added Platform

const AppState = NativeModules.AppState;
const tag = "BackgroundJob:";
const jobModule = NativeModules.BackgroundJob;
if (Platform.OS === 'ios') jobModule = {}; // added this line
const nativeJobs = jobModule.jobs;
var jobs = {};
var globalWarning = __DEV__;
```

I think something like this might be helpful for others as well. 

Thanks!
RB

**Comment by rbembleton** [comment]
And to clarify, it seems that the BackgroundJob Native Module isn't properly being linked...

**Comment by vikeri** [comment]
You're right, I should probably add that logic so that the module is not imported when on iOS.
