### ISSUE TITLE
Background start not allowed: service Intent ...

### ISSUE THREAD

**Issue by mppperez** [vikeri/react-native-background-job#131]
Changing to targetSdkVersion 28 I'm getting following error if the job is tried to be started when application were closed/killed:

2019-07-16 14:36:08.592 1757-1974/system_process W/ActivityManager: Background start not allowed: service Intent { flg=0x4 cmp=xxx/com.pilloxa.backgroundjob.ExactJob (has extras) } to xxx/com.pilloxa.backgroundjob.ExactJob from pid=-1 uid=10080 pkg=xxx

With target 27 everything worked fine. Now that we wanted to lift all dependencies and the target for the next release were facing this issue.

Anyone else already fixed this or any suggestions?

Configuration:
```
const myBackgroundJob = {
		jobKey: "myBackgroundJob",
		job: () => {
				console.log('myBackgroundJob');
			});
		}
	};

	BackgroundJob.register(myBackgroundJob);

	let myBackgroundJobConfiguration = {
		jobKey: "myBackgroundJob",
		period: 60 * 1000, // The frequency to run the job with (in ms).
		allowWhileIdle: true, // Allow the scheduled job to execute also while it is in doze mode. (optional, default false)
		allowExecutionInForeground: false,
		networkType: BackgroundJob.NETWORK_TYPE_ANY,
		exact: true
	};

	BackgroundJob.schedule(myBackgroundJobConfiguration);
```

Changing allowExectutionInForeground will lead to the same error.

With target 26 everything has worked fine.

**Comment by showtan001** [comment]
Are you sure that 26 killed APP BackgroundJob still exists? how could it exist

**Comment by mppperez** [comment]
Hi,

target 28 were affected in my case. Since we don't use the library anymore I can't tell if the issue still exist.

I will close this issue since I cannot test it. You may open a new one or reopen if necessary.

BR
