### ISSUE TITLE
react native 61.5 android build fail

### ISSUE THREAD

**Issue by KoreanThinker** [vikeri/react-native-background-job#154]
> Task :react-native-background-job:compileReleaseJavaWithJavac FAILED
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\ReactNativeEventStarter.java:7: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\BackgroundJobModule.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\ExactJob.java:6: 
error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\Utils.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\ReactNativeEventStarter.java:29: error: cannot find symbol
  public ReactNativeEventStarter(@NonNull Context context) {
                                  ^
  symbol:   class NonNull
  location: class ReactNativeEventStarter
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\ReactNativeEventStarter.java:34: error: cannot find symbol
  public void trigger(@NonNull Bundle jobBundle) {
                       ^
  symbol:   class NonNull
  location: class ReactNativeEventStarter
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\BackgroundJobModule.java:146: error: cannot find symbol
  @Nullable @Override public Map<String, Object> getConstants() {
   ^
  symbol:   class Nullable
  location: class BackgroundJobModule
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\ExactJob.java:14: error: cannot find symbol
  @Override protected void onHandleIntent(@Nullable Intent intent) {
                                           ^
  symbol:   class Nullable
  location: class ExactJob
C:\Users\HYUN\project\alert_scheduler\app\node_modules\react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\Utils.java:14: error: cannot find symbol
  public static boolean isReactNativeAppInForeground(@NonNull ReactNativeHost reactNativeHost) {
                                                      ^
  symbol:   class NonNull
  location: class Utils
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-background-job:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

I using "react-native-background-job": "^2.3.1"  and I can't read JAVA help me please.

**Comment by ahmetozel** [comment]
Unfortunately I have same problem..

@KoreanThinker did you fix it?

**Comment by KoreanThinker** [comment]
@ahmetozel  
it's problem about androidx
open the node_modules/react-native-background-job and update JAVA files
```java
import android.support.annotation.Nullable;    // change this line
import androidx.annotation.Nullable;    // like this
```
according to error message you should change 5 line in java file

**Comment by Cauen** [comment]
This lib uses some resources added in version 26 of API
For example: https://developer.android.com/reference/android/app/NotificationChannel
In my case, changing sdk version to 28 works

**Comment by sanchezfauste** [comment]
Same problem, @KoreanThinker workaround works for me.
