### ISSUE TITLE
Does this work for iOS?

### ISSUE THREAD

**Issue by Jacse** [vikeri/react-native-background-job#28]
According to the readme only Android is supported but the project also has an iOS Xcode-project. So does it work on both platforms? If so, I think the readme should be updated to reflect support.

**Comment by vikeri** [comment]
As it says in the readme it does not support iOS, the xcode project is just there because it was from the scaffolded RN project.

**Comment by Jacse** [comment]
@vikeri okay cool, thanks for clearing that up.

**Comment by appsthatmatter** [comment]
@Jacse fyi: take a look at react-native-background-task when you are looking for iOS alternative

**Comment by Noitidart** [comment]
@jjoe64 thanks for that! I was looking for this for ios!
