### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by MaximilianKindshofer** [vikeri/react-native-background-job#3]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/maximilian/code/chaosdoor/node_modules/react-native-background-job/android/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':react-native-background-job'.
> No such property: incremental for class: com.android.build.gradle.internal.CompileOptions_Decorated

I went to line 15 and deleted the the option wich led me to the next problem:

Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [chaosdoor:react-native-background-job:unspecified] /home/maximilian/code/chaosdoor/android/app/build/intermediates/exploded-aar/chaosdoor/react-native-background-job/unspecified/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.pilloxa.backgroundjob" to force usage

So I upgraded the minSdkVersion in my android/app/build.gradle to 21.

Now it is compiling

**Comment by vikeri** [comment]
Ok, so to be clear, when you bumped your minSdkVersion it worked? I specify the minimum Android version to the readme. But I guess instructions to bump it in the gradle file should be added as well.

**Comment by MaximilianKindshofer** [comment]
In the **package** I had to delete the following line

 `compileOptions.incremental = false` from `android/build.gradle`

and I had to bump the minSdkVersion to 21 in **my projects** `android/app/build.gradle`

**Comment by vikeri** [comment]
Interesting, I added `compileOptions.incremental = false` to the package just because my compilations were failing, but only updating minSdkVersion `android/app/build.gradle` in your project did not fix the issue?

**Comment by MaximilianKindshofer** [comment]
I am not sure if it had worked the other way round - I first fixed the problem with the compile Option and then ran into the SdkVersion error

**Comment by vikeri** [comment]
Ok, could you try adding the `compileOptions.incremental = false` back and see if it compiles now that you have raised the sdkVersion?

**Comment by MaximilianKindshofer** [comment]
Ok I tried this and now Iam back at
> No such property: incremental for class: com.android.build.gradle.internal.CompileOtions_Decorated

**Comment by vikeri** [comment]
Alright thanks for troubleshooting, obviously an issue with the package then. If you can submit a PR fixing that it'd be great. Otherwise I'll have a look at it during the week.
