### ISSUE TITLE
Losing handle to jobs after app termination & restart

### ISSUE THREAD

**Issue by brwelch** [vikeri/react-native-background-job#40]
First, really appreciate this library, it's been great.

One issue I've run into is losing the handle to a job such that duplicate executions can occur. Here's how it happens:

- I have a alwaysRunning job registered/scheduled. Using v1.2.4.

BackgroundJob.register({
  jobKey: 'jobkey',
  job: processingFunction
})

BackgroundJob.schedule({
      jobKey: 'jobkey',
      period: 1000
      timeout: 3000,
      alwaysRunning: true,
      persist: false
 })

- When the app is placed into the background or terminated, the job executes. All good there. When I return from the background, the job execution ceases as expected.

- However, in the case of a terminated app, if I then restart it (i.e. click on the icon on Android home, re-enter the app, etc), the handle to the previous job execution is lost yet it keeps executing despite the app having returned to an active state.

- I noticed this because I started seeing API calls at a more frequent rate (issued from my job) due to multiple jobs being executed but all for the same app (just different instances).

- I attempted to first check via a getAll to ensure no other registered jobs, this returned no entries (even though the job was actually running). I also attempted cancel and cancelAll which also did not find the running job.

**Comment by vikeri** [comment]
Do you mean that it is executing in the foreground? There are some issues with `alwaysRunning` and we will probably replace it with an `exact` mode in `v.2.0.0`. If you wish to try it out already please try adding `react-native-background-job@2.0.0-0`

**Comment by brwelch** [comment]
It seems to *think* that the app is still in a terminated state when in fact I've restarted my app (so the job keeps running, I can't cancel it). I'll give 2.0.0 a try.

**Comment by vikeri** [comment]
Ok, weird. And before you try 2.0.0, what current version are you using?

**Comment by brwelch** [comment]
I'm using 1.2.4. I just tried 2.0.0, this issue is not exhibited which is great. I'm seeing something funky with the intervals, it seems like from logcat that RNBJ is executing at the exact intervals, but my API calls seem to be at scattered times (which was fine in 1.2.4) - this could be on my end and will investigate. Though are there any known issues with V2 exact mode in terms of the intervals? 

Also, it looks like it's now possible to have multiple exact jobs (as opposed to only one alwaysRunning) and they can also run in the foreground? (appreciating that these should be concise units of work so as to not freeze the app)

**Comment by vikeri** [comment]
I have just started evaluating v2 and I'm not personally using exact mode. But I tried it and it worked. A way to debug is to fork this project and try the example project and see if you have the same issues there. 
Yes they can run in the foreground, I haven't tested multiple exact jobs since I did not develop that feature.

**Comment by brwelch** [comment]
Thanks a lot. What branch/repo is the v2 code on?

**Comment by vikeri** [comment]
It's in this PR: https://github.com/vikeri/react-native-background-job/pull/38 Can I close the issue btw?

**Comment by brwelch** [comment]
Thanks; yes given that 2.0 solves it. Appreciate all the quick responses.

**Comment by vikeri** [comment]
👍
