### ISSUE TITLE
Job doesn't start again after restarting the phone

### ISSUE THREAD

**Issue by brafdlog** [vikeri/react-native-background-job#41]
Hi,
I am scheduling a job like so:
```
var backgroundSchedule = {
        jobKey: BACKGROUND_JOB_KEY,
        timeout: 5000,
        period: 9999999,
        alwaysRunning: true,
        notificationTitle: str('notificationTitle'),
        notificationIcon: 'ic_infinity',
        persist: true
}

BackgroundJob.schedule(backgroundSchedule);
```

The job runs in the background and the notification is on. But, after restarting the phone, the job doesn't start again.
Tried this on a few android phones.

Any ideas?

**Comment by vikeri** [comment]
You specified that it should run every 3 hours. Did you wait that long
after restart?

Den ons 19 juli 2017 12:24Jonathan <notifications@github.com> skrev:

**Comment by brafdlog** [comment]
@vikeri Thanks for the quick response.
That may be the issue. I will try to reduce the time and see if this really is the issue.

**Comment by brafdlog** [comment]
Nope, changed the period to 10000, the job runs before restart but doesn't run after restart.
What do you think?

**Comment by brafdlog** [comment]
@vikeri  Well, I see now that eventually it does turn on after restart. It takes a while (much more that the 10 seconds period) but it does turn on in the end.
Thats good enough for my use case.
Thanks!

**Comment by vikeri** [comment]
Ok!

ons 19 juli 2017 kl 21:36 skrev Jonathan <notifications@github.com>:

**Comment by L3V147H4N** [comment]
I have the same issue, Job is not starting after restart, job was schedule every 5000ms... and after more than 20 min still nothing

Does the 'restart' param works on the debub app?

**Comment by kishansbs** [comment]
job not start after restart
