### ISSUE TITLE
error: cannot find symbol                new BackgroundJobPackage()

### ISSUE THREAD

**Issue by aelallam** [vikeri/react-native-background-job#43]
In the manual installation there is a step : 
Add new BackgroundJobPackage() to the list returned by the getPackages() method in MainApplication.java

However when I build on android it gives me the error: 
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\...\Desktop\React Native\neck\android\app\src\main\java\com\neck\MainApplication.java:26: error: cannot find symbol
               new BackgroundJobPackage()
                   ^
  symbol: class BackgroundJobPackage
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

should I remove the line from MainApplication.java??

**Comment by vikeri** [comment]
I haven't actually used the manual installation but always just use `react-native link react-native-background-job` is there a reason you don't use that option?
