### ISSUE TITLE
_reactNativeBackgroundJob2.default.getAll is not a function

### ISSUE THREAD

**Issue by vrpruthvi** [vikeri/react-native-background-job#45]
`BackgroundJob.getAll();` doesn't seem to work.

**Comment by yins2017** [comment]
the error "getAll is not a function"
using command "npm install react-native-background-job --save" to download packet have something wrong(can't find function getAll in [project_dir]/node_modules/react-native-background-job/index.js)
my solution:
download react-native-background-job.zip directly install of using npm command

**Comment by vikeri** [comment]
Hmm, can you show me which version you got?

**Comment by vikeri** [comment]
Sorry, accidentally published a beta version as latest. Please uninstall and reinstall the package.
```yarn remove react-native-background-job && yarn add react-native-background-job```
or
```npm uninstall react-native-background-job --save && npm install react-native-background-job --save```

**Comment by vikeri** [comment]
If you continue to use `1.2.4` this should not be an issue but in `2.0.0` this method has been deprecated.

**Comment by nicatasa** [comment]
Same error happens with version 2.2.0. please help

**Comment by menarayanzshrestha** [comment]
```
BackgroundJob.getAll({
      callback: () => {
        SmsListener.addListener(message => {
          this.setState({lastMessage: message.body});
         
        });
      },
    });
```
What we should we use instead of getAll() if it is deprecated ?

"react-native-background-job": "^2.3.1"

**Comment by ramkgunturu** [comment]
anyone have got any idea what we used instead of getAll if is deprecated??
Instead of changing the version?
