### ISSUE TITLE
Crash after close app

### ISSUE THREAD

**Issue by pawellewandowski** [vikeri/react-native-background-job#5]
Hello,
If app is in background everything work fine. If I close app, crash message pops up every period time:
RN 0.40
Android 6.0

Code:
`        const backgroundJob = {
         jobKey: "speedtask",
         job: () => {
           console.log('error');
         }
        };
        BackgroundJob.cancelAll();
        BackgroundJob.register(backgroundJob);
        BackgroundJob.schedule({jobKey: 'speedtask', period: 5000, timeout: 30000 })

`

Can you paste working code ?

**Comment by vikeri** [comment]
Hi! Working code can be found here: [index.android.js](https://github.com/vikeri/react-native-background-job/blob/master/example/index.android.js)

Could you provide more details on the error that you get?

**Comment by pawellewandowski** [comment]
My full code: 
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  DeviceEventEmitter
} from 'react-native';
import BackgroundJob from 'react-native-background-job';

export default class a extends Component {
  componentDidMount(){
    const backgroundJob = {
     jobKey: "myJob",
     job: () => console.log("Running in background")
    };

    BackgroundJob.register(backgroundJob);

    var backgroundSchedule = {
     jobKey: "myJob",
     timeout: 5000,
     period: 5000,
    }

    BackgroundJob.schedule(backgroundSchedule);
  }

  render() {
    return (
      <View style={styles.container}>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('a', () => a);
`

If app is in background everything work fine. When I closed app I have error: 
'ExceptionsManager.js:63 No task registered for key myJob'

AppRegistry.js line 136.

**Comment by vikeri** [comment]
When running in HeadlessJS mode the react components are never mounted, so you have to put `BackgroundJob.register` outside of the class definition like done here: https://github.com/vikeri/react-native-background-job/blob/master/example/index.android.js#L20-L23

Also, when pasting longer chunks of code, use triple backtick ``` to comment out a whole section. I updated your answer to do that.

**Comment by Cynigo** [comment]
@vikeri So you can't really compare data to a state?

**Comment by vikeri** [comment]
@Cynigo I'm not sure I understand the question

**Comment by Cynigo** [comment]
@vikeri My bad, I was in school.
Basically, I was asking whether I could have a background job fetch data every x minutes and compare it to the data in the state of a component.
I'm just using the AsyncStorage now and it works wonderfully, thanks for this module!

**Comment by vikeri** [comment]
That's correct, no components are mounted in the background and hence no
component state can be accessed. Happy you like it!

ons 1 mars 2017 kl 09:33 skrev Manuel Kraus <notifications@github.com>:
