### ISSUE TITLE
Crashing after App is Closed

### ISSUE THREAD

**Issue by sircEUNHO** [vikeri/react-native-background-job#51]
So basically, i stumbled this on api 25.. i put my `register` outside the class while the `schedule` inside componentDidMount. But after closing the app(not existing on background), my app crashes. this is my code:

```
BackgroundJob.register({
    jobKey: "userNotif",
    job: () => {
        console.log('registered');
    }
});


export default class VeevMobile extends Component {
    componentDidMount() {
        BackgroundJob.schedule({
          jobKey: 'userNotif',
          period: 10000,
          timeout: 10000,
          allowExecutionInForeground: false,
        });
   }
}
```

I hope you can help me asap thanks 🥂

**Comment by vikeri** [comment]
The code looks good so in order to debug please provide a stack trace or the error message thrown.

**Comment by sircEUNHO** [comment]
@vikeri i fixed it right now, i guess it was because of the period I set. I'll close this right now

**Comment by yusuf987** [comment]
Sircunho What period have set ?
