### ISSUE TITLE
allowExecutionInForeground doesn't work

### ISSUE THREAD

**Issue by alexey-kuznetsov** [vikeri/react-native-background-job#54]
There is no option to start job in foreground now. Option 'allowExecutionInForeground' doesn't affect anything. And this is reason:
` if (appInForeground) {
        return null;
      }`

I found it in ReactNativeEventStarter.java, and when I commented these lines, all works properly.

**Comment by vikeri** [comment]
I don't personally use that option so please submit a PR with the fix 👍

**Comment by alexey-kuznetsov** [comment]
Done!

**Comment by vikeri** [comment]
Fixed by #56
