### ISSUE TITLE
Background jobs never running (Android)

### ISSUE THREAD

**Issue by joshjconlin** [vikeri/react-native-background-job#55]
I'm trying to get run some code in the background when the app is closed. I start up the app and get the console log saying the job has been scheduled, but then after i exit the code never seems to run and I can't find it in my phones list of processes/services. 

This is the code, am I using the package incorrectly?

```import BackgroundJob from 'react-native-background-job';
import FCM from 'react-native-fcm';
import { Alert } from 'react-native';
import * as AuthService from './app/services/auth';
import BadgeAndroid from './native_modules/BadgeAndroid';

import Index from './index.ios';

BackgroundJob.register({
  jobKey: 'pushListener',
  timeout: 15000,
  job: async () => {
    const fcmToken = await FCM.getFcmToken();
    const response = await AuthService.fetchBadgeCount(fcmToken);
    Alert.alert(JSON.stringify(response.data));
    BadgeAndroid.setBadge(response.data.data.attributes.badge_count);
  },
});

BackgroundJob.register({
  jobKey: 'testAlert',
  job: () => {
    Alert.alert('test')
  },
});

BackgroundJob.schedule({ jobKey: 'pushListener' });
BackgroundJob.schedule({ jobKey: 'testAlert' });

export default Index;
```

**Comment by vikeri** [comment]
Please refer to the example project, that code works: https://github.com/vikeri/react-native-background-job/blob/master/example/index.android.js

**Comment by joshjconlin** [comment]
just being able to console.log in the background isn't very useful if thats all it can do

**Comment by vikeri** [comment]
It can naturally do more things, I doubt the `Alert` method will fire in the background though. And how are you sure that the events are not run in the background?

**Comment by joshjconlin** [comment]
I've tried it with Vibration as well, and nothing. I'm sure its not running because its not doing what its supposed to. Its supposed to poll a server and then update the app icon's badge count (Which is also Java code). It never does it though. I actually ended up switching packages to https://github.com/jamesisaac/react-native-background-task and it works just fine with their package

**Comment by vikeri** [comment]
Interesting! Happy to hear that worked for you
