### ISSUE TITLE
Exception thrown while job is fired

### ISSUE THREAD

**Issue by holyxiaoxin** [vikeri/react-native-background-job#57]
Running reference [example](https://github.com/vikeri/react-native-background-job/blob/master/example/index.android.js) app on latest react-native build. 

"react": "16.0.0-alpha.12",
"react-native": "0.48.2",
"react-native-background-job": "^2.0.0"

Exception: Expected to run on UI thread!
![2017-09-12 21 54 13](https://user-images.githubusercontent.com/5796213/30329473-f146edc2-9804-11e7-87d2-b55dfcd2a136.jpg)

```js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import BackgroundJob from 'react-native-background-job';

const myJobKey = "myJobKey";

BackgroundJob.register({
 jobKey: myJobKey,
 job: () => {
   console.log("Running in background");
   console.log((new Date).toString());
 }
});

export default class BackgroundJobApp extends Component {
  componentDidMount() {
    BackgroundJob.schedule({
     jobKey: myJobKey,
     period: 900000,
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('BackgroundJob', () => BackgroundJobApp);
```

**Comment by Armageddonas** [comment]
I am facing the same problem

`package.json`
``` json
"react": "16.0.0-alpha.12",
"react-native": "0.48.2",
"react-native-background-job": "^2.0.0"
```

Maybe it is related with this https://github.com/facebook/react-native/issues/15915

**Comment by vikeri** [comment]
I haven't tried the latest RN versions, but that bug seems to be related for sure.

**Comment by RailtonMatthew** [comment]
Getting the same issue on RN 0.48.3.  Also, react-native-background-timer not longer works with this release.  I wonder if the issues are related.

Need to find a fix for running a function in background, otherwise my app is useless. :(

**Comment by Armageddonas** [comment]
Version `0.48.4` is released and is working properly for me

``` json
"react": "16.0.0-alpha.12",
"react-native": "0.48.4",
"react-native-background-job": "2.0.1"
```

**Comment by RailtonMatthew** [comment]
Just upgraded so my version match yours and still get the error.  It runs fine until the app goes into background mode.  

When in background the logs show the app starting up from scratch every time the job fires.  So, when is background it's like the app is completely shut down.

```
ReactInstanceManager.ctor()
ReactInstanceManager.createReactContextInBackground()
ReactInstanceManager.recreateReactContextInBackgroundInner()
ReactInstanceManager.onJSBundleLoadedFromServer()
ReactInstanceManager.recreateReactContextInBackground()
ReactInstanceManager.runCreateReactContextOnNewThread()
ReactInstanceManager.createReactContext()
Initializing React Xplat Bridge.
Initializing React Xplat Bridge before initializeBridge
Initializing React Xplat Bridge after initializeBridge
CatalystInstanceImpl.runJSBundle()
ReactInstanceManager.setupReactContext()
CatalystInstanceImpl.initialize()

```

I'm running Android.

**Comment by Armageddonas** [comment]
@RailtonMatthew My mistake, I edited my comment.

**Comment by barteksiudak** [comment]
I have this same problem. I'm writing my first App and this library is most important thing for me :(
Any ideas ? Which version of RN work with background-job ?

**Comment by Armageddonas** [comment]
Version `0.47.2` works fine for me.

**Comment by barteksiudak** [comment]
I will try today, thanks for answer @Armageddonas

**Comment by dheerajvarshney** [comment]
Yes When I changes version of "react-native": "0.47.2" - to "react-native": "^0.48.3" Its worked..
Thanks Armageddonas.

**Comment by vikeri** [comment]
I'll mark this as closed then. Please comment if it should be reopened.

**Comment by artemukolov** [comment]
Still have this problem in my project
   "react-native": "^0.48.3",
   "react-native-background-job": "^2.0.1"
Is there any solutions to fix it?

**Comment by dheerajvarshney** [comment]
Changes version in package.json file 

"react-native": "^0.47.2" to "react-native": "^0.48.3" then Uninstall/delete nodeModules folder  from path. 
and run npm install from existing app cmd. hope all will work

**Comment by artemukolov** [comment]
No. This.doesn't work. Do you really have no errors like "expected to run on UI thread" when app is closed ??

**Comment by dheerajvarshney** [comment]
Yes, I fixed and my app is working when app will closed and jobs is running in background.

also make sure when app is running in back ground there is no UI related for update - like alert and any Updation in UI

**Comment by artemukolov** [comment]
"Closed" you mean just in background? Or removed from task manager? Did you try it?

**Comment by dheerajvarshney** [comment]
Yes both in process in, also  removed from task manager - its working

**Comment by dheerajvarshney** [comment]
can you let me know all package.json file

**Comment by artemukolov** [comment]
So, I noticed this behaviour: 
- I downloaded example from your repository and tried to run it - all ok (there is RN - ^0.45.1)
- Changed version to 0.48.4 and started app. And I faced with same error when I closed app vie task manager: "expected to run on UI thread"

Looks like there are incompatible code.

**Comment by artemukolov** [comment]
One more thing: Working good with RN:0.49.5. I will try to use this version in my project. 
Thanks for answers. Good library, by the way.

**Comment by dheerajvarshney** [comment]
Thanks..

**Comment by L3V147H4N** [comment]
Updated to RN 0.50.0 ... issue seems fixed
