### ISSUE TITLE
List of all scheduled jobs

### ISSUE THREAD

**Issue by tizzyapunkt** [vikeri/react-native-background-job#58]
Is it possible to get a list of scheduled jobs and their configurations? 
Possible use case might be to check if a job is scheduled and override it with new config if needed.

PS. Great package. Thank you!

**Comment by vikeri** [comment]
Hi, unfortunately since we migrated to Firebase Jobdispatcher this feature has been removed since that dispatcher does not provide that feature. A suggestion is to just re-schedule it all the time (since it will by default override previous configurations).

**Comment by tizzyapunkt** [comment]
Okay, thank you for the quick response.
