### ISSUE TITLE
new version without Google Play Services

### ISSUE THREAD

**Issue by cbjs** [vikeri/react-native-background-job#59]
Does this new version(2.x.x) work on devices without google play services?

**Comment by vikeri** [comment]
No it does not unfortunately

**Comment by cbjs** [comment]
yeah, most devices in China do not shipped with google play services.

**Comment by vikeri** [comment]
Right, that's unfortuntate. Our app is initially only targeting Europe though so for me it made more sense to use the Play Services version. The `1.2.x` version was still working though. And I could patch it and release bug fixes if PR's come in targeting that branch.

**Comment by cbjs** [comment]
thanks~ @vikeri
