### ISSUE TITLE
All tasks has pauses in execution

### ISSUE THREAD

**Issue by artemukolov** [vikeri/react-native-background-job#63]
When I tried to run you example app on me machine, then I see that all tasks has pauses during execution. And doesn't matter, job in background or not. On screen shot log of react-native example app. There in one of several pauses between 14:50:17.725 and 14:54:53 
![screen shot 2017-11-09 at 14 58 13](https://user-images.githubusercontent.com/11043617/32604763-dd9543ae-c55f-11e7-9545-af49dd54db1c.png)

Is it fixable? Thank you

**Comment by vikeri** [comment]
What do you mean by pauses?

**Comment by artemukolov** [comment]
absence of iteration

**Comment by vikeri** [comment]
I see, well unfortunately you can't rely on the library firing at exact times. Sometimes Android won't let it run.

**Comment by artemukolov** [comment]
ok. Also I noticed jobs with allowExecutionInForeground: true has more weird behaviour. They stoped after 15-20 iterations at all.

**Comment by vikeri** [comment]
Interesting, I don't personally use the `allowExecutionInForeground` options since it's discouraged by the devs and ideally should only be used for debugging. Does it happen consistently or did you only encounter it once?

**Comment by artemukolov** [comment]
consistently. This going in your example app. Did you try to check it?
(I use real device.)

**Comment by artemukolov** [comment]
So. you said that you don't use allowExecutionInForeground: true.
How yoou use one job for background and foreground?

**Comment by vikeri** [comment]
I use Bluetooth so in the foreground I'm constantly connected and in the background I periodically wake up to check if there is any new data available from the peripheral. In the foreground a simple `setInterval`works for recurring tasks.

Also, I created an issue for the foreground tasks. Closing this one.

**Comment by jussirantala** [comment]
https://developer.android.com/training/monitoring-device-state/doze-standby.html

https://developer.android.com/reference/android/app/AlarmManager.html#setExactAndAllowWhileIdle(int, long, android.app.PendingIntent)
