### ISSUE TITLE
"allowWhileIdle" option needed to run while in Doze

### ISSUE THREAD

**Issue by jussirantala** [vikeri/react-native-background-job#66]
I found out that my background job doesn't run while in doze mode (Android 7.0) if using exact timing mode. I think it could be fixed by adding an option for _schedule()_ to use _setExactAndAllowWhileIdle_ instead of _setExact_

https://developer.android.com/training/monitoring-device-state/doze-standby.html

> Standard AlarmManager alarms (including setExact() and setWindow()) are deferred to the next maintenance window.
> - If you need to set alarms that fire while in Doze, use setAndAllowWhileIdle() or setExactAndAllowWhileIdle().
> - Alarms set with setAlarmClock() continue to fire normally — the system exits Doze shortly before those alarms fire.

**Comment by jussirantala** [comment]
The task does run though (by looking at logs via wifi adb) but there's no network connection available for the app. The socket connects as soon as I turn on the display.

**Comment by jussirantala** [comment]
I tried _setExactAndAllowWhileIdle_ and the behavior was the same. From Android logs I can see that Android puts the app into doze mode but the job wakes it up but there's not network available.

**Comment by vikeri** [comment]
I think I've seen this too. I'm busy with other things at the moment though. But if you submit a PR that would be great!

**Comment by jussirantala** [comment]
I see you've added this feature :)
