### ISSUE TITLE
Task not fired

### ISSUE THREAD

**Issue by thiagoferolla** [vikeri/react-native-background-job#67]
I've copied the example project into my app but when i tried to run the background task was never fired.
I got on the console that the task was successfully scheduled but when the app entered background mode, nothing happens.

**Comment by vikeri** [comment]
Are you sure you don't have any battery saving mode running?

Could you provide some information about your platform:
- RN Version
- Android Version
- Android model

**Comment by thiagoferolla** [comment]
I'm using a Galaxy S7 with Android N. React Native 0.50.3. The task is actually working but it's taking more than 15 minutes to be fired for the first time, after that it's fine.

**Comment by vikeri** [comment]
Ok, as stated in the readme this library does not guarantee exact execution intervals so I'm closing this.
