### ISSUE TITLE
Call the task dynamically

### ISSUE THREAD

**Issue by thanhminh6996** [vikeri/react-native-background-job#69]
Hi, i'm working with Firebase, i want to when the database has new data, job will be called, how can i do that?
This is Firebase code:

```javascript
comments.on('child_added', function(data) {
  addCommentElement(data);
  // job_run(); Job will be callled
});
```
Thanks.

**Comment by vikeri** [comment]
This library is for running periodic jobs, so not for on demand tasks unfortunately.
