### ISSUE TITLE
Bluetooth Scanning Stops but timestamp continues

### ISSUE THREAD

**Issue by rgstephens** [vikeri/react-native-background-job#75]
I created a sample react-native-background-job app [here](https://github.com/rgstephens/RNBackgroundJobBLE) that registers and then schedules a job to run every 10 seconds. The job both writes a timestamp to a Redux store and also calls the [react-native-ble-plx](https://github.com/Polidea/react-native-ble-plx) bluetooth library to scan for devices for 2 seconds.

When the app loses focus, the timestamps continue to be written to the Redux store but the scanning no longer works.  Log messages for the scanning show it starting every 10 seconds and stopping after the 2 second setTimeout but no devices are found when the app is in the background.

I currently have the `allowExecutionInForeground` option enabled but even with this option disabled, there are no results from the background scan.

**index.js**

```
const backgroundJob = {
  jobKey: "timestamp",
  job: () => myJob("background")
};
BackgroundJob.register(backgroundJob);
var backgroundSchedule = {
  jobKey: "timestamp",
  period: scanInterval,
  exact: true,
  allowExecutionInForeground: true,
  allowWhileIdle: true
};
BackgroundJob.schedule(backgroundSchedule);
AppRegistry.registerComponent("ForegroundTest", () => App);
```

**myJob**
```
function myJob(callerName) {
  let diff = Number.MAX_SAFE_INTEGER;
  if (lastRun) {
    const diff = new Date() - lastRun;
    //ms = new Date(diff).toISOString().slice(14, 21);
  }
  if ((diff + 500) >= scanInterval) {
    console.log("run from " + callerName + ", " + new Date());
    store.dispatch({ type: "TIMESTAMP" });
    doScan(scanLength);
  } else {
    console.log(
      "suppressing run from " + callerName + ", " + (diff + 500) + " >= " + scanInterval
    );
  }
  lastRun = new Date();
}
```

**doScan**
```
export function doScan(scanTime) {
  let deviceList = [];
  if (!bleManager) {
    console.log('--- first scanning call, instantiate new BleManager');
    bleManager = new BleManager({
      restoreStateIdentifier: 'foregroundTest',
      restoreStateFunction: (bleRestoredState) => {
        console.log('restoreStateFunction called');
      },
    });
  }

  // Set timer to stop scan
  setTimeout(function() {
    console.log('<<< stopping scan, ', new Date());
    if (bleManager) {
      bleManager.stopDeviceScan();
    }
  }, scanTime);

  // Start scan
  bleManager.startDeviceScan(null, null, (error, device) => {
    if (error) {
      // Handle error (scanning will be stopped automatically)
      console.log('bleScan error, stopping - ', error);
      return;
    }
    if (!deviceList.includes(device.id)) {
      console.log('add device:', device.id, ', deviceList:', deviceList);
      deviceList.push(device.id);  
      store.dispatch({ type: 'DEVICE', device: device });
    }
  });
}
```

**Comment by vikeri** [comment]
@rgstephens We used to use https://github.com/innoveit/react-native-ble-manager and it worked, but not reliably enough for us so we have rewritten our Bluetooth setup in the native layer for better performance. But try that library first to see if it works.

**Comment by rgstephens** [comment]
@vikeri Thanks for the pointer, I'll give that a try!

**Comment by rgstephens** [comment]
@vikeri I'm having the same issue with react-native-ble-manager and I'm wondering if this is somehow associated with trying to do scans vs. maintaining a connection to a BLE device. Maybe this would work for a connected BLE device but not for scanning.

**Comment by vikeri** [comment]
@rgstephens As I said before, we have transitioned to a fully native stack for our bluetooth setup due to the pure js solution not being performant enough. That being said, we accomplished background scanning using the library I referenced earlier so I don't know what your issue might be.

**Comment by vikeri** [comment]
I don't think this is related to this library btw, so I'm closing this for now.
