### ISSUE TITLE
scheduled Job is not working in background mode...

### ISSUE THREAD

**Issue by subham18meme** [vikeri/react-native-background-job#82]
Hi,
I'm using a Eventlistener which read a tag. But when i use that Read method in 
 BackgroundJob.schedule({
        **job:this.readTag()**,
        jobKey: exactJobKey,
        period: 1000,
        timeout: 10000,
        exact: true,
        allowWhileIdle:true
      });
in that way Job is not working.
If there is any mistake or suggestion will be very helpful, and i really need this as soon as possible

**Comment by vikeri** [comment]
`job:this.readTag()` should probably be `job:this.readTag` unless the `readTag` method returns another function.
