### ISSUE TITLE
How can we add dynamic frequency based on job runs 

### ISSUE THREAD

**Issue by Afsarunnisa** [vikeri/react-native-background-job#84]
Is it possible to change the frequency of the job, based on some job handlers ?

our app is fetching location based on users current location,  if user is near to some destination location we need pool the location frequently. if not we have to increase the job running time,

**Comment by vikeri** [comment]
Yes, you can just run schedule again with another period.

**Comment by Afsarunnisa** [comment]
we can run same schedule in job method only ?

**Comment by vikeri** [comment]
I don't understand the question
