### ISSUE TITLE
Bug for android 6

### ISSUE THREAD

**Issue by achimbaggins** [vikeri/react-native-background-job#87]
doJob(key, time) {
    let Key = key == 'kurirJobKey' ? 'kurirJobKey' : 'feederJobKey'
    BackgroundJob.register({
      jobKey: key == 'kurirJobKey' ? kurirJobKey : feederJobKey,
      job: () => {
        this.pushNotif(Key, time)
      },
    })
    BackgroundJob.schedule({
      jobKey: key == 'kurirJobKey' ? kurirJobKey : feederJobKey,
      period: 15000,
      exact: false,
      allowWhileIdle: true,
      allowExecutionInForeground: true,
    })
  }

exact: false ==> it's mean that BJ do nothing when app is closed, 
int android 7 it's run as expected, but in android 6 this BJ still executed so my app getting crash...
it's a bug or anything to do?

**Comment by vikeri** [comment]
No `exact=false` means that it runs as normal. If you don't want to run it then use the method `cancel`.

**Comment by achimbaggins** [comment]
oh thank you for your suggestion... when my component unmount I cancel the job...  I'll try it

**Comment by vikeri** [comment]
Ok! Closing this issue for now.
