### ISSUE TITLE
Got error when in apk-release

### ISSUE THREAD

**Issue by creativefull** [vikeri/react-native-background-job#9]
hi friend, when in develop its work, but when i compile my project to apk-release i got error like this
![16736648_120300002079936928_49178595_n](https://cloud.githubusercontent.com/assets/13174684/22862242/b2501fa6-f15d-11e6-8535-70e985372bf2.png)

can you help me friend ?

**Comment by vikeri** [comment]
Interesting, I'll investigate

**Comment by hkairi** [comment]
`const nativeJobs = jobModule.jobs;` returns undefined on production APK

**Comment by vikeri** [comment]
@hkari Interesting, can you provide which version of RN you are using?

**Comment by hkairi** [comment]
@vikeri i am using 0.40.0. But now i am having the issue with "tried to start task while in foreground" when i run on production mode

**Comment by hkairi** [comment]
@creativefull @vikeri 
fixed in this commit : 

[https://github.com/hkairi/react-native-background-job/commit/54a6f52b283fd4ad741289d014350c268001c537](url)

**Comment by creativefull** [comment]
@hkairi your link not found

**Comment by hkairi** [comment]
@creativefull https://github.com/hkairi/react-native-background-job/

**Comment by vikeri** [comment]
Did a pre-release with @hkairi's PR: https://github.com/vikeri/react-native-background-job/releases/tag/v1.1.2-0

Install with 
```
yarn add react-native-background-job@beta
```

As soon as we've confirmed the fix in our app I'll release it to latest.

**Comment by vikeri** [comment]
Tested in production for a while and it works. Released: https://github.com/vikeri/react-native-background-job/releases/tag/v1.1.2
Thanks @hkairi

**Comment by creativefull** [comment]
OK thank you very much (Y)
