### ISSUE TITLE
APP is not sending data after proper time interval always.

### ISSUE THREAD

**Issue by Tanumay92** [vikeri/react-native-background-job#90]
My purpose is to send the data in server in every 15 minutes. Its working fine. But in some case the time interval between two frequency of the job is changing. Say, sometime it happens in 17 mins and some cases it completely not working.

**Comment by vikeri** [comment]
Android background jobs are not designed to be exact unfortunately. So that's a limitation of the platform rather than this library. Closing since there's nothing I can do about it.
