### ISSUE TITLE
Bacground Job is not working in case of xioami devices

### ISSUE THREAD

**Issue by Tanumay92** [vikeri/react-native-background-job#91]
In all devices its atleast working. But for xioami dvices its not working properly at all. Any solution??

**Comment by vikeri** [comment]
I have tested it on Xiaomi and it worked. I'd need some more info of what doesn't work to be able to work on this one. Closing for now.

**Comment by MahmoudElmoghazy** [comment]
In Xiaomi phones you will found in settings options that execute all background service close this option and it will work fine
