### ISSUE TITLE
Unable to set networkType

### ISSUE THREAD

**Issue by judemanutd** [vikeri/react-native-background-job#93]
I am trying to set a `networkType` for the background task but I'm not sure how.

Using the following code crashes the app with the error being 
`com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.Double`

```
import BackgroundJob, {NETWORK_TYPE_ANY} from 'react-native-background-job';

export const initBackgroundTask = () => {

    BackgroundJob.cancelAll();

    BackgroundJob.schedule({
        jobKey: regularJobKey,
        networkType: {NETWORK_TYPE_ANY},
        period: getDurationPeriod() * 1000
    });
};
```

The documentation says I need to specify a number, I require a network connection to exist, the default is -1 so should this be 1?

**Comment by vikeri** [comment]
Could you try 
```js
networkType: NETWORK_TYPE_ANY
```

**Comment by judemanutd** [comment]
Unfortunately the need for background sync was removed as a requirement for the app so I cannot test it now but will let you know if I ever do, so please feel free to close the issue if needed.

**Comment by vikeri** [comment]
Ok, closing this for now.
