### ISSUE TITLE
How to run job on a certain time?

### ISSUE THREAD

**Issue by winglight** [vikeri/react-native-background-job#97]
I'm not sure this lib has this feature for no example like this in the docs. Here's my requirement:
1.Set a certain time to trigger a job(it's just to send a local notification, in fact)
2.Cancel all jobs sometimes

Any hint will be appreciated!

**Comment by vikeri** [comment]
If you want to send a local notification it's better to schedule it using some of the notification libraries. This library is more for repeating background tasks.
